#  Copyright 2025 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: Validate All 3rd Party Mediation Adapters

on:
  pull_request:
    branches: [ main ]

  # Trigger workflow manually from Actions tab
  workflow_dispatch:
jobs:
  test-adapter:

    # Run for each adapter listed in the matrix below
    runs-on: macos-latest
    continue-on-error: true
    timeout-minutes: 30 

    strategy:
      matrix:
        adapter:
          # Update this adapter list with the ThirdPartyAdapter name 
          # This allows this action to test the adapter
          - applovin
          - bidmachine
          - chartboost
          - dtexchange
          - imobile
          - inmobi
          - ironsource
          - liftoffmonetize
          - line
          - maio
          - meta
          - mintegral
          - moloco
          - mytarget
          - pangle
          - pubmatic
          - unity
          - verve
          # Future adapters here
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Install Gradle"
        run: |
          brew install gradle
      - name: "Run Unit Tests for ${{ matrix.adapter }}"
        run: |
          cd ThirdPartyAdapters/${{ matrix.adapter }}/
          gradle wrapper
          ./gradlew test --scan